import { buildSpectrePatch } from '../lib/spectre-tiling.js';

/**
 * Spectre Diffraction Bloom
 *
 * Built around the Spectre — the single tile discovered in 2023 that covers
 * the plane only in non-repeating, one-handed arrangements. The patch here
 * is generated by the tile's real hierarchical substitution system (depth 4,
 * 4401 spectres), and the scene morphs between:
 *
 *   1. DIRECT SPACE — flying over the interlocking stained-glass tiling,
 *      colored by substitution ancestry so the hierarchy reads as regions.
 *   2. RECIPROCAL SPACE — the tiling's actual Fourier diffraction pattern:
 *      tile centers are rasterized into a 512x512 grid (Hann-windowed), run
 *      through a real 2D FFT once at startup, displayed as log(1+I), and its
 *      extracted Bragg peaks fly past the camera as a star tunnel.
 *
 * Audio mapping: bass extrudes tiles into prisms and breathes the zoom;
 * beats launch an inflation wave that lights the substitution hierarchy
 * outward from the view center; mids pulse coherent regions (per-ancestor
 * weights); treble sharpens peaks, adds edge sparks and chromatic split;
 * the spectral centroid steers the direct/reciprocal crossfade (with a slow
 * autonomous cycle so both worlds always get seen); silence settles it all
 * back into a flat, dim, mathematically exact tiling.
 */

const LABEL_HUE = {
  Gamma1: 268, Gamma2: 288, Delta: 210, Theta: 186, Lambda: 46,
  Xi: 322, Pi: 148, Sigma: 24, Phi: 250, Psi: 96,
};

export class SpectreBloom {
  constructor() {
    this.name = 'Spectre Diffraction Bloom';
    const { tiles, bounds } = buildSpectrePatch(4);
    this.tiles = tiles;
    this.bounds = bounds;
    this.cx0 = (bounds.minX + bounds.maxX) / 2;
    this.cy0 = (bounds.minY + bounds.maxY) / 2;
    this.span = Math.min(bounds.maxX - bounds.minX, bounds.maxY - bounds.minY);

    for (const t of tiles) {
      const path = new Path2D();
      path.moveTo(t.points[0], t.points[1]);
      for (let i = 1; i < 14; i++) path.lineTo(t.points[i * 2], t.points[i * 2 + 1]);
      path.closePath();
      t.path = path;
      t.hue = LABEL_HUE[t.label] ?? 200;
      t.r1 = t.parents[0];                     // coarse substitution region (8)
      t.r2 = t.parents[0] * 8 + t.parents[1];  // finer region (64)
    }

    this.waves = []; // beat inflation waves
    this.morph = 0;
    this.centroidS = 0;
    this.bassS = 0;
    this.midS = 0;
    this.trebS = 0;
    this.travel = 0;
    this.diffReady = false;
    this.peaks = [];
    setTimeout(() => this._computeDiffraction(), 400);
  }

  // ================= reciprocal space (computed once) =================

  _computeDiffraction() {
    const N = 512;
    const re = new Float64Array(N * N);
    const im = new Float64Array(N * N);

    // rasterize tile centers over the central window, Hann-weighted so the
    // patch boundary doesn't smear the peaks
    const L = this.span * 0.75;
    const R = L / 2;
    for (const t of this.tiles) {
      const dx = t.cx - this.cx0;
      const dy = t.cy - this.cy0;
      const r = Math.hypot(dx, dy);
      if (r > R) continue;
      const gx = Math.round(((dx + R) / L) * (N - 1));
      const gy = Math.round(((dy + R) / L) * (N - 1));
      re[gy * N + gx] += 0.5 * (1 + Math.cos((Math.PI * r) / R));
    }

    // in-place 2D FFT: rows, then columns
    const rowRe = new Float64Array(N);
    const rowIm = new Float64Array(N);
    for (let y = 0; y < N; y++) {
      rowRe.set(re.subarray(y * N, y * N + N));
      rowIm.fill(0);
      fft(rowRe, rowIm);
      re.set(rowRe, y * N);
      im.set(rowIm, y * N);
    }
    const colRe = new Float64Array(N);
    const colIm = new Float64Array(N);
    for (let x = 0; x < N; x++) {
      for (let y = 0; y < N; y++) {
        colRe[y] = re[y * N + x];
        colIm[y] = im[y * N + x];
      }
      fft(colRe, colIm);
      for (let y = 0; y < N; y++) {
        re[y * N + x] = colRe[y];
        im[y * N + x] = colIm[y];
      }
    }

    // log intensity, fftshifted so DC sits at the center
    const v = new Float32Array(N * N);
    let vMax = 0;
    const half = N / 2;
    for (let y = 0; y < N; y++) {
      for (let x = 0; x < N; x++) {
        const sy = (y + half) % N;
        const sx = (x + half) % N;
        const i = sy * N + sx;
        const inten = re[i] * re[i] + im[i] * im[i];
        const lv = Math.log1p(inten);
        v[y * N + x] = lv;
        const dc = Math.hypot(x - half, y - half) < 4;
        if (!dc && lv > vMax) vMax = lv;
      }
    }

    // colored texture: deep indigo -> violet -> cyan-white
    const canvas = document.createElement('canvas');
    canvas.width = canvas.height = N;
    const cctx = canvas.getContext('2d');
    const img = cctx.createImageData(N, N);
    for (let i = 0; i < N * N; i++) {
      // subtract the diffuse floor and steepen: peaks pop on near-black
      const raw = Math.min(1, v[i] / vMax);
      const x = Math.pow(Math.max(0, (raw - 0.3) / 0.7), 1.6);
      const p = i * 4;
      img.data[p] = Math.round(6 + 110 * x + 140 * x * x * x);
      img.data[p + 1] = Math.round(4 + 50 * x + 200 * x * x * x);
      img.data[p + 2] = Math.round(16 + 200 * x * x + 45 * x);
      img.data[p + 3] = 255;
    }
    cctx.putImageData(img, 0, 0);
    // fade the square's edges so the pattern melts into space
    const mask = cctx.createRadialGradient(N / 2, N / 2, N * 0.3, N / 2, N / 2, N * 0.5);
    mask.addColorStop(0, 'rgba(0,0,0,0)');
    mask.addColorStop(1, 'rgba(0,0,0,1)');
    cctx.globalCompositeOperation = 'destination-out';
    cctx.fillStyle = mask;
    cctx.fillRect(0, 0, N, N);
    cctx.globalCompositeOperation = 'source-over';
    this.diffCanvas = canvas;

    // extract Bragg peaks (local maxima) for the star tunnel
    const peaks = [];
    for (let y = 2; y < N - 2; y++) {
      for (let x = 2; x < N - 2; x++) {
        const val = v[y * N + x];
        if (val < vMax * 0.42) continue;
        if (Math.hypot(x - half, y - half) < 7) continue;
        let isMax = true;
        for (let dy = -1; dy <= 1 && isMax; dy++) {
          for (let dx = -1; dx <= 1; dx++) {
            if (dx === 0 && dy === 0) continue;
            if (v[(y + dy) * N + (x + dx)] > val) { isMax = false; break; }
          }
        }
        if (isMax) peaks.push({ x, y, val });
      }
    }
    peaks.sort((a, b) => b.val - a.val);
    this.peaks = peaks.slice(0, 260).map((p) => ({
      kx: (p.x - half) / half,
      ky: (p.y - half) / half,
      inten: Math.min(1, p.val / vMax),
      z0: Math.random(),
    }));
    this.diffReady = true;
  }

  // ================= per-frame =================

  draw({ ctx, audio, w, h, dt, t }) {
    // audio features
    const active = audio.musicActive ? 1 : 0;
    this.bassS += (audio.bass * active - this.bassS) * Math.min(1, 3 * dt);
    this.midS += (audio.mid * active - this.midS) * Math.min(1, 4 * dt);
    this.trebS += (audio.treb * active - this.trebS) * Math.min(1, 5 * dt);

    // spectral centroid (0..1) steers the space crossfade
    let num = 0;
    let den = 0;
    const bins = Math.floor(audio.freq.length * 0.5);
    for (let i = 0; i < bins; i++) {
      num += i * audio.freq[i];
      den += audio.freq[i];
    }
    const centroid = den > 40 ? num / den / bins : 0;
    this.centroidS += (centroid - this.centroidS) * Math.min(1, 1.2 * dt);

    // slow autonomous cycle guarantees both worlds get stage time
    const lfo = 0.5 - 0.5 * Math.cos((t * 2 * Math.PI) / 55);
    let target = Math.max(0, Math.min(1, lfo * 0.7 + (this.centroidS - 0.07) * 3.2 - 0.12));
    if (!audio.musicActive || !this.diffReady) target = 0; // silence: settle into the exact tiling
    this.morph += (target - this.morph) * Math.min(1, 0.5 * dt * (1 + audio.beatPulse));
    const m = this.morph;

    if (audio.beat) {
      this.waves.push({ age: 0 });
      if (this.waves.length > 4) this.waves.shift();
    }
    for (const wv of this.waves) wv.age += dt;
    this.waves = this.waves.filter((wv) => wv.age < 1.4);

    ctx.fillStyle = '#05030f';
    ctx.fillRect(0, 0, w, h);

    if (m < 0.97) this._drawDirect(ctx, audio, w, h, dt, t, 1 - m * 0.9, m);
    if (m > 0.03 && this.diffReady) this._drawReciprocal(ctx, audio, w, h, dt, t, m);
  }

  _drawDirect(ctx, audio, w, h, dt, t, alpha, m) {
    // camera: drift across the patch, breathe through the hierarchy on bass
    const drift = 1 - m * 0.7;
    const camX = this.cx0 + Math.sin(t * 0.023) * this.span * 0.16 * drift;
    const camY = this.cy0 + Math.sin(t * 0.017 + 2.1) * this.span * 0.16 * drift;
    const zoomBreath = 1 + Math.sin(t * 0.05) * 0.28;
    const scale = (Math.min(w, h) / 34) * zoomBreath * (1 + this.bassS * 0.45);
    const rot = t * 0.012;

    ctx.save();
    ctx.globalAlpha = alpha;
    ctx.translate(w / 2, h / 2);
    ctx.rotate(rot);
    ctx.scale(scale, scale);
    ctx.translate(-camX, -camY);

    const viewR = Math.hypot(w, h) / 2 / scale + 3;
    const viewR2 = viewR * viewR;
    const sat = 20 + 45 * Math.min(1, audio.level * 3);
    const extrude = this.bassS > 0.12 ? (this.bassS * 5) / scale : 0;
    const lineW = 1.6 / scale;
    const waveSpeed = 55;

    ctx.lineWidth = lineW;
    for (const tile of this.tiles) {
      const dx = tile.cx - camX;
      const dy = tile.cy - camY;
      const d2 = dx * dx + dy * dy;
      if (d2 > viewR2) continue;

      // inflation wave: hierarchy lights up outward from the view center
      let waveGlow = 0;
      if (this.waves.length) {
        const dist = Math.sqrt(d2);
        for (const wv of this.waves) {
          const rr = wv.age * waveSpeed;
          const band = Math.abs(dist - rr);
          if (band < 7) waveGlow = Math.max(waveGlow, (1 - band / 7) * Math.max(0, 1 - wv.age));
        }
      }

      // mids pulse coherent substitution regions without touching geometry
      const pulse = this.midS * (0.5 + 0.5 * Math.sin(t * 2.2 + tile.r2 * 1.71));
      const light = 16 + pulse * 20 + waveGlow * 34 + this.trebS * 4;
      const hue = (tile.hue + tile.r1 * 9 + t * 3) % 360;

      if (extrude > 0.01) {
        ctx.save();
        ctx.translate(extrude, extrude * 1.4);
        ctx.fillStyle = `hsla(${hue}, ${sat * 0.6}%, ${Math.max(3, light * 0.35)}%, 1)`;
        ctx.fill(tile.path);
        ctx.restore();
      }
      ctx.fillStyle = `hsla(${hue}, ${sat}%, ${light}%, 1)`;
      ctx.fill(tile.path);
      ctx.strokeStyle = waveGlow > 0.04
        ? `hsla(${(hue + 40) % 360}, 95%, ${55 + waveGlow * 35}%, ${0.35 + waveGlow})`
        : `hsla(${hue}, ${sat}%, ${Math.min(60, light + 14)}%, 0.55)`;
      ctx.stroke(tile.path);
    }

    // treble edge sparks: random tile edges catch the light
    const sparks = Math.floor(this.trebS * 26);
    if (sparks > 0) {
      ctx.lineWidth = lineW * 2.2;
      ctx.lineCap = 'round';
      for (let i = 0; i < sparks; i++) {
        const tile = this.tiles[(Math.random() * this.tiles.length) | 0];
        const dx = tile.cx - camX;
        const dy = tile.cy - camY;
        if (dx * dx + dy * dy > viewR2) continue;
        const e = (Math.random() * 14) | 0;
        const e2 = (e + 1) % 14;
        ctx.strokeStyle = `hsla(${(tile.hue + 140) % 360}, 100%, 78%, ${0.5 + this.trebS * 0.5})`;
        ctx.beginPath();
        ctx.moveTo(tile.points[e * 2], tile.points[e * 2 + 1]);
        ctx.lineTo(tile.points[e2 * 2], tile.points[e2 * 2 + 1]);
        ctx.stroke();
      }
    }
    ctx.restore();
    ctx.globalAlpha = 1;
  }

  _drawReciprocal(ctx, audio, w, h, dt, t, m) {
    const cx = w / 2;
    const cy = h / 2;
    const size = Math.hypot(w, h) * (1.05 + this.bassS * 0.12);

    // the measured diffraction pattern, slowly rotating
    ctx.save();
    ctx.globalAlpha = m * (0.9 - this.trebS * 0.2);
    ctx.translate(cx, cy);
    ctx.rotate(t * 0.008);
    ctx.drawImage(this.diffCanvas, -size / 2, -size / 2, size, size);
    ctx.restore();

    // Bragg-peak star tunnel: every diffraction peak streams past the camera
    this.travel += dt * (0.1 + audio.level * 0.55 + audio.beatPulse * 0.55);
    const reach = Math.min(w, h) * 0.62;
    const split = this.trebS * 5;
    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    for (const p of this.peaks) {
      const z = ((p.z0 - this.travel) % 1 + 1) % 1;
      const persp = 0.06 / (z + 0.05);
      const px = cx + p.kx * persp * reach;
      const py = cy + p.ky * persp * reach;
      const persp2 = 0.06 / (z + 0.09);
      const qx = cx + p.kx * persp2 * reach;
      const qy = cy + p.ky * persp2 * reach;
      const fade = Math.min(1, (1 - z) * 1.6) * Math.min(1, z * 14);
      const a = fade * p.inten * m;
      if (a < 0.02) continue;
      const rad = (0.8 + p.inten * 2.2) * (0.4 + persp) * (1 - this.trebS * 0.35);

      // streak toward the camera
      ctx.strokeStyle = `hsla(${205 + p.inten * 90 + this.trebS * 40}, 90%, ${60 + p.inten * 25}%, ${a * 0.8})`;
      ctx.lineWidth = rad;
      ctx.lineCap = 'round';
      ctx.beginPath();
      ctx.moveTo(qx, qy);
      ctx.lineTo(px, py);
      ctx.stroke();

      // chromatic split on the hot peaks when the top end is busy
      if (split > 0.4 && p.inten > 0.6) {
        ctx.fillStyle = `hsla(0, 95%, 65%, ${a * 0.35})`;
        ctx.fillRect(px - split - rad / 2, py - rad / 2, rad, rad);
        ctx.fillStyle = `hsla(195, 95%, 65%, ${a * 0.35})`;
        ctx.fillRect(px + split - rad / 2, py - rad / 2, rad, rad);
      }
    }
    ctx.restore();

    // central beam bloom pulses with the beat
    const g = ctx.createRadialGradient(cx, cy, 0, cx, cy, Math.min(w, h) * (0.06 + audio.beatPulse * 0.05));
    g.addColorStop(0, `hsla(220, 100%, 88%, ${m * (0.5 + audio.beatPulse * 0.5)})`);
    g.addColorStop(1, 'transparent');
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, w, h);
  }
}

/** In-place iterative radix-2 complex FFT. */
function fft(re, im) {
  const n = re.length;
  for (let i = 1, j = 0; i < n; i++) {
    let bit = n >> 1;
    for (; j & bit; bit >>= 1) j ^= bit;
    j |= bit;
    if (i < j) {
      let tmp = re[i]; re[i] = re[j]; re[j] = tmp;
      tmp = im[i]; im[i] = im[j]; im[j] = tmp;
    }
  }
  for (let len = 2; len <= n; len <<= 1) {
    const ang = (-2 * Math.PI) / len;
    const wr = Math.cos(ang);
    const wi = Math.sin(ang);
    for (let i = 0; i < n; i += len) {
      let cr = 1;
      let ci = 0;
      for (let k = 0; k < len / 2; k++) {
        const ar = re[i + k];
        const ai = im[i + k];
        const br = re[i + k + len / 2] * cr - im[i + k + len / 2] * ci;
        const bi = re[i + k + len / 2] * ci + im[i + k + len / 2] * cr;
        re[i + k] = ar + br;
        im[i + k] = ai + bi;
        re[i + k + len / 2] = ar - br;
        im[i + k + len / 2] = ai - bi;
        const ncr = cr * wr - ci * wi;
        ci = cr * wi + ci * wr;
        cr = ncr;
      }
    }
  }
}
